(define list-length ; Finds the Length of a list
    (lambda (l) ;lambda definition
      (cond ;conditional loop to determine list size
	((null? l) 0)
	(#t (+ 1 (list-length (cdr l))))))) ; end of function

(define (gen-table var_list) ;defines the gen-table funtion
	(if (eq? (list-length var_list) 0) ; checks for 0 arguments and outputs
		() ;null list return
	(if (< (list-length var_list) 2) ; checks for 1 arguments and outputs
		'((#t) (#f))
	(if (< (list-length var_list) 3) ; checks for 2 arguments and outputs
		'( ( #f #f ) ( #f #t ) ( #t #f ) ( #t #t ))
	(if (< (list-length var_list) 4)	; checks for 3 arguments and outputs
	'((#f #f #f) (#f #f #t) (#f #t #f) (#f #t #t) 
	(#t #f #f) (#t #f #t) (#t #t #f) (#t #t #t) )
	(if (< (list-length var_list) 5) ; checks for 4 arguments and outputs
	'((#f #f #f #f) (#f #f #f #t) (#f #f #t #f) (#f #f #t #t) 
	(#f #t #f #f) (#f #t #f #t) (#f #t #t #f) (#f #t #t #t) 
	(#t #f #f #f) (#t #f #f #t) (#t #f #t #f) (#t #f #t #t)
	(#t #t #f #f) (#t #t #f #t) (#t #t #t #f) (#t #t #t #t) )
	(if (< (list-length var_list) 6) ; checks for 5 arguments and outputs
	'((#f #f #f #f #f) (#f #f #f #f #t) (#f #f #f #t #f) (#f #f #f #t #t) 
	  (#f #f #t #f #f) (#f #f #t #f #t) (#f #f #t #t #f) (#f #f #t #t #t) 
	  (#f #t #f #f #f) (#f #t #f #f #t) (#f #t #f #t #f) (#f #t #f #t #t) 
	  (#f #t #t #f #f) (#f #t #t #f #t) (#f #t #t #t #f) (#f #t #t #t #t) 
	  (#t #f #f #f #f) (#t #f #f #f #t) (#t #f #f #t #f) (#t #f #f #t #t) 
	  (#t #f #t #f #f) (#t #f #t #f #t) (#t #f #t #t #f) (#t #f #t #t #t) 
	  (#t #t #f #f #f) (#t #t #f #f #t) (#t #t #f #t #f) (#t #t #f #t #t) 
	  (#t #t #t #f #f) (#t #t #t #f #t) (#t #t #t #t #f) (#t #t #t #t #t) )
	  (if (< (list-length var_list) 7) ; checks for 6 arguments and outputs
	  '((#f #f #f #f #f #f) (#f #f #f #f #f #t) (#f #f #f #f #t #f) (#f #f #f #f #t #t) 
		(#f #f #f #t #f #f) (#f #f #f #t #f #t) (#f #f #f #t #t #f) (#f #f #f #t #t #t) 
		(#f #f #t #f #f #f) (#f #f #t #f #f #t) (#f #f #t #f #t #f) (#f #f #t #f #t #t) 
		(#f #f #t #t #f #f) (#f #f #t #t #f #t) (#f #f #t #t #t #f) (#f #f #t #t #t #t) 
		(#f #t #f #f #f #f) (#f #t #f #f #f #t) (#f #t #f #f #t #f) (#f #t #f #f #t #t) 
		(#f #t #f #t #f #f) (#f #t #f #t #f #t) (#f #t #f #t #t #f) (#f #t #f #t #t #t) 
		(#f #t #t #f #f #f) (#f #t #t #f #f #t) (#f #t #t #f #t #f) (#f #t #t #f #t #t) 
		(#f #t #t #t #f #f) (#f #t #t #t #f #t) (#f #t #t #t #t #f) (#f #t #t #t #t #t) 
		(#t #f #f #f #f #f) (#t #f #f #f #f #t) (#t #f #f #f #t #f) (#t #f #f #f #t #t) 
		(#t #f #f #t #f #f) (#t #f #f #t #f #t) (#t #f #f #t #t #f) (#t #f #f #t #t #t) 
		(#t #f #t #f #f #f) (#t #f #t #f #f #t) (#t #f #t #f #t #f) (#t #f #t #f #t #t) 
		(#t #f #t #t #f #f) (#t #f #t #t #f #t) (#t #f #t #t #t #f) (#t #f #t #t #t #t) 
		(#t #t #f #f #f #f) (#t #t #f #f #f #t) (#t #t #f #f #t #f) (#t #t #f #f #t #t) 
		(#t #t #f #t #f #f) (#t #t #f #t #f #t) (#t #t #f #t #t #f) (#t #t #f #t #t #t) 
		(#t #t #t #f #f #f) (#t #t #t #f #f #t) (#t #t #t #f #t #f) (#t #t #t #f #t #t) 
		(#t #t #t #t #f #f) (#t #t #t #t #f #t) (#t #t #t #t #t #f) (#t #t #t #t #t #t) )
		(if (< (list-length var_list) 8) ; checks for7 arguments and outputs
		'((#f #f #f #f #f #f #f) (#f #f #f #f #f #f #t) (#f #f #f #f #f #t #f) (#f #f #f #f #f #t #t) 
(#f #f #f #f #t #f #f) (#f #f #f #f #t #f #t) (#f #f #f #f #t #t #f) (#f #f #f #f #t #t #t) 
(#f #f #f #t #f #f #f) (#f #f #f #t #f #f #t) (#f #f #f #t #f #t #f) (#f #f #f #t #f #t #t) 
(#f #f #f #t #t #f #f) (#f #f #f #t #t #f #t) (#f #f #f #t #t #t #f) (#f #f #f #t #t #t #t) 
(#f #f #t #f #f #f #f) (#f #f #t #f #f #f #t) (#f #f #t #f #f #t #f) (#f #f #t #f #f #t #t) 
(#f #f #t #f #t #f #f) (#f #f #t #f #t #f #t) (#f #f #t #f #t #t #f) (#f #f #t #f #t #t #t) 
(#f #f #t #t #f #f #f) (#f #f #t #t #f #f #t) (#f #f #t #t #f #t #f) (#f #f #t #t #f #t #t) 
(#f #f #t #t #t #f #f) (#f #f #t #t #t #f #t) (#f #f #t #t #t #t #f) (#f #f #t #t #t #t #t) 
(#f #t #f #f #f #f #f) (#f #t #f #f #f #f #t) (#f #t #f #f #f #t #f) (#f #t #f #f #f #t #t) 
(#f #t #f #f #t #f #f) (#f #t #f #f #t #f #t) (#f #t #f #f #t #t #f) (#f #t #f #f #t #t #t) 
(#f #t #f #t #f #f #f) (#f #t #f #t #f #f #t) (#f #t #f #t #f #t #f) (#f #t #f #t #f #t #t) 
(#f #t #f #t #t #f #f) (#f #t #f #t #t #f #t) (#f #t #f #t #t #t #f) (#f #t #f #t #t #t #t) 
(#f #t #t #f #f #f #f) (#f #t #t #f #f #f #t) (#f #t #t #f #f #t #f) (#f #t #t #f #f #t #t) 
(#f #t #t #f #t #f #f) (#f #t #t #f #t #f #t) (#f #t #t #f #t #t #f) (#f #t #t #f #t #t #t) 
(#f #t #t #t #f #f #f) (#f #t #t #t #f #f #t) (#f #t #t #t #f #t #f) (#f #t #t #t #f #t #t) 
(#f #t #t #t #t #f #f) (#f #t #t #t #t #f #t) (#f #t #t #t #t #t #f) (#f #t #t #t #t #t #t) 
(#t #f #f #f #f #f #f) (#t #f #f #f #f #f #t) (#t #f #f #f #f #t #f) (#t #f #f #f #f #t #t) 
(#t #f #f #f #t #f #f) (#t #f #f #f #t #f #t) (#t #f #f #f #t #t #f) (#t #f #f #f #t #t #t) 
(#t #f #f #t #f #f #f) (#t #f #f #t #f #f #t) (#t #f #f #t #f #t #f) (#t #f #f #t #f #t #t) 
(#t #f #f #t #t #f #f) (#t #f #f #t #t #f #t) (#t #f #f #t #t #t #f) (#t #f #f #t #t #t #t) 
(#t #f #t #f #f #f #f) (#t #f #t #f #f #f #t) (#t #f #t #f #f #t #f) (#t #f #t #f #f #t #t) 
(#t #f #t #f #t #f #f) (#t #f #t #f #t #f #t) (#t #f #t #f #t #t #f) (#t #f #t #f #t #t #t) 
(#t #f #t #t #f #f #f) (#t #f #t #t #f #f #t) (#t #f #t #t #f #t #f) (#t #f #t #t #f #t #t) 
(#t #f #t #t #t #f #f) (#t #f #t #t #t #f #t) (#t #f #t #t #t #t #f) (#t #f #t #t #t #t #t) 
(#t #t #f #f #f #f #f) (#t #t #f #f #f #f #t) (#t #t #f #f #f #t #f) (#t #t #f #f #f #t #t) 
(#t #t #f #f #t #f #f) (#t #t #f #f #t #f #t) (#t #t #f #f #t #t #f) (#t #t #f #f #t #t #t) 
(#t #t #f #t #f #f #f) (#t #t #f #t #f #f #t) (#t #t #f #t #f #t #f) (#t #t #f #t #f #t #t) 
(#t #t #f #t #t #f #f) (#t #t #f #t #t #f #t) (#t #t #f #t #t #t #f) (#t #t #f #t #t #t #t) 
(#t #t #t #f #f #f #f) (#t #t #t #f #f #f #t) (#t #t #t #f #f #t #f) (#t #t #t #f #f #t #t) 
(#t #t #t #f #t #f #f) (#t #t #t #f #t #f #t) (#t #t #t #f #t #t #f) (#t #t #t #f #t #t #t) 
(#t #t #t #t #f #f #f) (#t #t #t #t #f #f #t) (#t #t #t #t #f #t #f) (#t #t #t #t #f #t #t) 
(#t #t #t #t #t #f #f) (#t #t #t #t #t #f #t) (#t #t #t #t #t #t #f) (#t #t #t #t #t #t #t) )
		(if (< (list-length var_list) 9) ; checks for 8 arguments and outputs
		'((#f #f #f #f #f #f #f #f) (#f #f #f #f #f #f #f #t) (#f #f #f #f #f #f #t #f) (#f #f #f #f #f #f #t #t) 
(#f #f #f #f #f #t #f #f) (#f #f #f #f #f #t #f #t) (#f #f #f #f #f #t #t #f) (#f #f #f #f #f #t #t #t) 
(#f #f #f #f #t #f #f #f) (#f #f #f #f #t #f #f #t) (#f #f #f #f #t #f #t #f) (#f #f #f #f #t #f #t #t) 
(#f #f #f #f #t #t #f #f) (#f #f #f #f #t #t #f #t) (#f #f #f #f #t #t #t #f) (#f #f #f #f #t #t #t #t) 
(#f #f #f #t #f #f #f #f) (#f #f #f #t #f #f #f #t) (#f #f #f #t #f #f #t #f) (#f #f #f #t #f #f #t #t) 
(#f #f #f #t #f #t #f #f) (#f #f #f #t #f #t #f #t) (#f #f #f #t #f #t #t #f) (#f #f #f #t #f #t #t #t) 
(#f #f #f #t #t #f #f #f) (#f #f #f #t #t #f #f #t) (#f #f #f #t #t #f #t #f) (#f #f #f #t #t #f #t #t) 
(#f #f #f #t #t #t #f #f) (#f #f #f #t #t #t #f #t) (#f #f #f #t #t #t #t #f) (#f #f #f #t #t #t #t #t) 
(#f #f #t #f #f #f #f #f) (#f #f #t #f #f #f #f #t) (#f #f #t #f #f #f #t #f) (#f #f #t #f #f #f #t #t) 
(#f #f #t #f #f #t #f #f) (#f #f #t #f #f #t #f #t) (#f #f #t #f #f #t #t #f) (#f #f #t #f #f #t #t #t) 
(#f #f #t #f #t #f #f #f) (#f #f #t #f #t #f #f #t) (#f #f #t #f #t #f #t #f) (#f #f #t #f #t #f #t #t) 
(#f #f #t #f #t #t #f #f) (#f #f #t #f #t #t #f #t) (#f #f #t #f #t #t #t #f) (#f #f #t #f #t #t #t #t) 
(#f #f #t #t #f #f #f #f) (#f #f #t #t #f #f #f #t) (#f #f #t #t #f #f #t #f) (#f #f #t #t #f #f #t #t) 
(#f #f #t #t #f #t #f #f) (#f #f #t #t #f #t #f #t) (#f #f #t #t #f #t #t #f) (#f #f #t #t #f #t #t #t) 
(#f #f #t #t #t #f #f #f) (#f #f #t #t #t #f #f #t) (#f #f #t #t #t #f #t #f) (#f #f #t #t #t #f #t #t) 
(#f #f #t #t #t #t #f #f) (#f #f #t #t #t #t #f #t) (#f #f #t #t #t #t #t #f) (#f #f #t #t #t #t #t #t) 
(#f #t #f #f #f #f #f #f) (#f #t #f #f #f #f #f #t) (#f #t #f #f #f #f #t #f) (#f #t #f #f #f #f #t #t) 
(#f #t #f #f #f #t #f #f) (#f #t #f #f #f #t #f #t) (#f #t #f #f #f #t #t #f) (#f #t #f #f #f #t #t #t) 
(#f #t #f #f #t #f #f #f) (#f #t #f #f #t #f #f #t) (#f #t #f #f #t #f #t #f) (#f #t #f #f #t #f #t #t) 
(#f #t #f #f #t #t #f #f) (#f #t #f #f #t #t #f #t) (#f #t #f #f #t #t #t #f) (#f #t #f #f #t #t #t #t) 
(#f #t #f #t #f #f #f #f) (#f #t #f #t #f #f #f #t) (#f #t #f #t #f #f #t #f) (#f #t #f #t #f #f #t #t) 
(#f #t #f #t #f #t #f #f) (#f #t #f #t #f #t #f #t) (#f #t #f #t #f #t #t #f) (#f #t #f #t #f #t #t #t) 
(#f #t #f #t #t #f #f #f) (#f #t #f #t #t #f #f #t) (#f #t #f #t #t #f #t #f) (#f #t #f #t #t #f #t #t) 
(#f #t #f #t #t #t #f #f) (#f #t #f #t #t #t #f #t) (#f #t #f #t #t #t #t #f) (#f #t #f #t #t #t #t #t) 
(#f #t #t #f #f #f #f #f) (#f #t #t #f #f #f #f #t) (#f #t #t #f #f #f #t #f) (#f #t #t #f #f #f #t #t) 
(#f #t #t #f #f #t #f #f) (#f #t #t #f #f #t #f #t) (#f #t #t #f #f #t #t #f) (#f #t #t #f #f #t #t #t) 
(#f #t #t #f #t #f #f #f) (#f #t #t #f #t #f #f #t) (#f #t #t #f #t #f #t #f) (#f #t #t #f #t #f #t #t) 
(#f #t #t #f #t #t #f #f) (#f #t #t #f #t #t #f #t) (#f #t #t #f #t #t #t #f) (#f #t #t #f #t #t #t #t) 
(#f #t #t #t #f #f #f #f) (#f #t #t #t #f #f #f #t) (#f #t #t #t #f #f #t #f) (#f #t #t #t #f #f #t #t) 
(#f #t #t #t #f #t #f #f) (#f #t #t #t #f #t #f #t) (#f #t #t #t #f #t #t #f) (#f #t #t #t #f #t #t #t) 
(#f #t #t #t #t #f #f #f) (#f #t #t #t #t #f #f #t) (#f #t #t #t #t #f #t #f) (#f #t #t #t #t #f #t #t) 
(#f #t #t #t #t #t #f #f) (#f #t #t #t #t #t #f #t) (#f #t #t #t #t #t #t #f) (#f #t #t #t #t #t #t #t) 
(#t #f #f #f #f #f #f #f) (#t #f #f #f #f #f #f #t) (#t #f #f #f #f #f #t #f) (#t #f #f #f #f #f #t #t) 
(#t #f #f #f #f #t #f #f) (#t #f #f #f #f #t #f #t) (#t #f #f #f #f #t #t #f) (#t #f #f #f #f #t #t #t) 
(#t #f #f #f #t #f #f #f) (#t #f #f #f #t #f #f #t) (#t #f #f #f #t #f #t #f) (#t #f #f #f #t #f #t #t) 
(#t #f #f #f #t #t #f #f) (#t #f #f #f #t #t #f #t) (#t #f #f #f #t #t #t #f) (#t #f #f #f #t #t #t #t) 
(#t #f #f #t #f #f #f #f) (#t #f #f #t #f #f #f #t) (#t #f #f #t #f #f #t #f) (#t #f #f #t #f #f #t #t) 
(#t #f #f #t #f #t #f #f) (#t #f #f #t #f #t #f #t) (#t #f #f #t #f #t #t #f) (#t #f #f #t #f #t #t #t) 
(#t #f #f #t #t #f #f #f) (#t #f #f #t #t #f #f #t) (#t #f #f #t #t #f #t #f) (#t #f #f #t #t #f #t #t) 
(#t #f #f #t #t #t #f #f) (#t #f #f #t #t #t #f #t) (#t #f #f #t #t #t #t #f) (#t #f #f #t #t #t #t #t) 
(#t #f #t #f #f #f #f #f) (#t #f #t #f #f #f #f #t) (#t #f #t #f #f #f #t #f) (#t #f #t #f #f #f #t #t) 
(#t #f #t #f #f #t #f #f) (#t #f #t #f #f #t #f #t) (#t #f #t #f #f #t #t #f) (#t #f #t #f #f #t #t #t) 
(#t #f #t #f #t #f #f #f) (#t #f #t #f #t #f #f #t) (#t #f #t #f #t #f #t #f) (#t #f #t #f #t #f #t #t) 
(#t #f #t #f #t #t #f #f) (#t #f #t #f #t #t #f #t) (#t #f #t #f #t #t #t #f) (#t #f #t #f #t #t #t #t) 
(#t #f #t #t #f #f #f #f) (#t #f #t #t #f #f #f #t) (#t #f #t #t #f #f #t #f) (#t #f #t #t #f #f #t #t) 
(#t #f #t #t #f #t #f #f) (#t #f #t #t #f #t #f #t) (#t #f #t #t #f #t #t #f) (#t #f #t #t #f #t #t #t) 
(#t #f #t #t #t #f #f #f) (#t #f #t #t #t #f #f #t) (#t #f #t #t #t #f #t #f) (#t #f #t #t #t #f #t #t) 
(#t #f #t #t #t #t #f #f) (#t #f #t #t #t #t #f #t) (#t #f #t #t #t #t #t #f) (#t #f #t #t #t #t #t #t) 
(#t #t #f #f #f #f #f #f) (#t #t #f #f #f #f #f #t) (#t #t #f #f #f #f #t #f) (#t #t #f #f #f #f #t #t) 
(#t #t #f #f #f #t #f #f) (#t #t #f #f #f #t #f #t) (#t #t #f #f #f #t #t #f) (#t #t #f #f #f #t #t #t) 
(#t #t #f #f #t #f #f #f) (#t #t #f #f #t #f #f #t) (#t #t #f #f #t #f #t #f) (#t #t #f #f #t #f #t #t) 
(#t #t #f #f #t #t #f #f) (#t #t #f #f #t #t #f #t) (#t #t #f #f #t #t #t #f) (#t #t #f #f #t #t #t #t) 
(#t #t #f #t #f #f #f #f) (#t #t #f #t #f #f #f #t) (#t #t #f #t #f #f #t #f) (#t #t #f #t #f #f #t #t) 
(#t #t #f #t #f #t #f #f) (#t #t #f #t #f #t #f #t) (#t #t #f #t #f #t #t #f) (#t #t #f #t #f #t #t #t) 
(#t #t #f #t #t #f #f #f) (#t #t #f #t #t #f #f #t) (#t #t #f #t #t #f #t #f) (#t #t #f #t #t #f #t #t) 
(#t #t #f #t #t #t #f #f) (#t #t #f #t #t #t #f #t) (#t #t #f #t #t #t #t #f) (#t #t #f #t #t #t #t #t) 
(#t #t #t #f #f #f #f #f) (#t #t #t #f #f #f #f #t) (#t #t #t #f #f #f #t #f) (#t #t #t #f #f #f #t #t) 
(#t #t #t #f #f #t #f #f) (#t #t #t #f #f #t #f #t) (#t #t #t #f #f #t #t #f) (#t #t #t #f #f #t #t #t) 
(#t #t #t #f #t #f #f #f) (#t #t #t #f #t #f #f #t) (#t #t #t #f #t #f #t #f) (#t #t #t #f #t #f #t #t) 
(#t #t #t #f #t #t #f #f) (#t #t #t #f #t #t #f #t) (#t #t #t #f #t #t #t #f) (#t #t #t #f #t #t #t #t) 
(#t #t #t #t #f #f #f #f) (#t #t #t #t #f #f #f #t) (#t #t #t #t #f #f #t #f) (#t #t #t #t #f #f #t #t) 
(#t #t #t #t #f #t #f #f) (#t #t #t #t #f #t #f #t) (#t #t #t #t #f #t #t #f) (#t #t #t #t #f #t #t #t) 
(#t #t #t #t #t #f #f #f) (#t #t #t #t #t #f #f #t) (#t #t #t #t #t #f #t #f) (#t #t #t #t #t #f #t #t) 
(#t #t #t #t #t #t #f #f) (#t #t #t #t #t #t #f #t) (#t #t #t #t #t #t #t #f) (#t #t #t #t #t #t #t #t) )
		(if (< (list-length var_list) 10) ; checks for 9 arguments and outputs
		'((#f #f #f #f #f #f #f #f #f) (#f #f #f #f #f #f #f #f #t) (#f #f #f #f #f #f #f #t #f) (#f #f #f #f #f #f #f #t #t) (#f #f #f #f #f #f #t #f #f) (#f #f #f #f #f #f #t #f #t) (#f #f #f #f #f #f #t #t #f) (#f #f #f #f #f #f #t #t #t) (#f #f #f #f #f #t #f #f #f) (#f #f #f #f #f #t #f #f #t) (#f #f #f #f #f #t #f #t #f) (#f #f #f #f #f #t #f #t #t) (#f #f #f #f #f #t #t #f #f) (#f #f #f #f #f #t #t #f #t) (#f #f #f #f #f #t #t #t #f) (#f #f #f #f #f #t #t #t #t) (#f #f #f #f #t #f #f #f #f) (#f #f #f #f #t #f #f #f #t) (#f #f #f #f #t #f #f #t #f) (#f #f #f #f #t #f #f #t #t) (#f #f #f #f #t #f #t #f #f) (#f #f #f #f #t #f #t #f #t) (#f #f #f #f #t #f #t #t #f) (#f #f #f #f #t #f #t #t #t) (#f #f #f #f #t #t #f #f #f) (#f #f #f #f #t #t #f #f #t) (#f #f #f #f #t #t #f #t #f) (#f #f #f #f #t #t #f #t #t) (#f #f #f #f #t #t #t #f #f) (#f #f #f #f #t #t #t #f #t) (#f #f #f #f #t #t #t #t #f) (#f #f #f #f #t #t #t #t #t) (#f #f #f #t #f #f #f #f #f) (#f #f #f #t #f #f #f #f #t) (#f #f #f #t #f #f #f #t #f) (#f #f #f #t #f #f #f #t #t) (#f #f #f #t #f #f #t #f #f) (#f #f #f #t #f #f #t #f #t) (#f #f #f #t #f #f #t #t #f) (#f #f #f #t #f #f #t #t #t) (#f #f #f #t #f #t #f #f #f) (#f #f #f #t #f #t #f #f #t) (#f #f #f #t #f #t #f #t #f) (#f #f #f #t #f #t #f #t #t) (#f #f #f #t #f #t #t #f #f) (#f #f #f #t #f #t #t #f #t) (#f #f #f #t #f #t #t #t #f) (#f #f #f #t #f #t #t #t #t) (#f #f #f #t #t #f #f #f #f) (#f #f #f #t #t #f #f #f #t) (#f #f #f #t #t #f #f #t #f) (#f #f #f #t #t #f #f #t #t) (#f #f #f #t #t #f #t #f #f) (#f #f #f #t #t #f #t #f #t) (#f #f #f #t #t #f #t #t #f) (#f #f #f #t #t #f #t #t #t) (#f #f #f #t #t #t #f #f #f) (#f #f #f #t #t #t #f #f #t) (#f #f #f #t #t #t #f #t #f) (#f #f #f #t #t #t #f #t #t) (#f #f #f #t #t #t #t #f #f) (#f #f #f #t #t #t #t #f #t) (#f #f #f #t #t #t #t #t #f) (#f #f #f #t #t #t #t #t #t) (#f #f #t #f #f #f #f #f #f) (#f #f #t #f #f #f #f #f #t) (#f #f #t #f #f #f #f #t #f) (#f #f #t #f #f #f #f #t #t) (#f #f #t #f #f #f #t #f #f) (#f #f #t #f #f #f #t #f #t) (#f #f #t #f #f #f #t #t #f) (#f #f #t #f #f #f #t #t #t) (#f #f #t #f #f #t #f #f #f) (#f #f #t #f #f #t #f #f #t) (#f #f #t #f #f #t #f #t #f) (#f #f #t #f #f #t #f #t #t) (#f #f #t #f #f #t #t #f #f) (#f #f #t #f #f #t #t #f #t) (#f #f #t #f #f #t #t #t #f) (#f #f #t #f #f #t #t #t #t) (#f #f #t #f #t #f #f #f #f) (#f #f #t #f #t #f #f #f #t) (#f #f #t #f #t #f #f #t #f) (#f #f #t #f #t #f #f #t #t) (#f #f #t #f #t #f #t #f #f) (#f #f #t #f #t #f #t #f #t) (#f #f #t #f #t #f #t #t #f) (#f #f #t #f #t #f #t #t #t) (#f #f #t #f #t #t #f #f #f) (#f #f #t #f #t #t #f #f #t) (#f #f #t #f #t #t #f #t #f) (#f #f #t #f #t #t #f #t #t) (#f #f #t #f #t #t #t #f #f) (#f #f #t #f #t #t #t #f #t) (#f #f #t #f #t #t #t #t #f) (#f #f #t #f #t #t #t #t #t) (#f #f #t #t #f #f #f #f #f) (#f #f #t #t #f #f #f #f #t) (#f #f #t #t #f #f #f #t #f) (#f #f #t #t #f #f #f #t #t) (#f #f #t #t #f #f #t #f #f) (#f #f #t #t #f #f #t #f #t) (#f #f #t #t #f #f #t #t #f) (#f #f #t #t #f #f #t #t #t) (#f #f #t #t #f #t #f #f #f) (#f #f #t #t #f #t #f #f #t) (#f #f #t #t #f #t #f #t #f) (#f #f #t #t #f #t #f #t #t) (#f #f #t #t #f #t #t #f #f) (#f #f #t #t #f #t #t #f #t) (#f #f #t #t #f #t #t #t #f) (#f #f #t #t #f #t #t #t #t) (#f #f #t #t #t #f #f #f #f) (#f #f #t #t #t #f #f #f #t) (#f #f #t #t #t #f #f #t #f) (#f #f #t #t #t #f #f #t #t) (#f #f #t #t #t #f #t #f #f) (#f #f #t #t #t #f #t #f #t) (#f #f #t #t #t #f #t #t #f) (#f #f #t #t #t #f #t #t #t) (#f #f #t #t #t #t #f #f #f) (#f #f #t #t #t #t #f #f #t) (#f #f #t #t #t #t #f #t #f) (#f #f #t #t #t #t #f #t #t) (#f #f #t #t #t #t #t #f #f) (#f #f #t #t #t #t #t #f #t) (#f #f #t #t #t #t #t #t #f) (#f #f #t #t #t #t #t #t #t) (#f #t #f #f #f #f #f #f #f) (#f #t #f #f #f #f #f #f #t) (#f #t #f #f #f #f #f #t #f) (#f #t #f #f #f #f #f #t #t) (#f #t #f #f #f #f #t #f #f) (#f #t #f #f #f #f #t #f #t) (#f #t #f #f #f #f #t #t #f) (#f #t #f #f #f #f #t #t #t) (#f #t #f #f #f #t #f #f #f) (#f #t #f #f #f #t #f #f #t) (#f #t #f #f #f #t #f #t #f) (#f #t #f #f #f #t #f #t #t) (#f #t #f #f #f #t #t #f #f) (#f #t #f #f #f #t #t #f #t) (#f #t #f #f #f #t #t #t #f) (#f #t #f #f #f #t #t #t #t) (#f #t #f #f #t #f #f #f #f) (#f #t #f #f #t #f #f #f #t) (#f #t #f #f #t #f #f #t #f) (#f #t #f #f #t #f #f #t #t) (#f #t #f #f #t #f #t #f #f) (#f #t #f #f #t #f #t #f #t) (#f #t #f #f #t #f #t #t #f) (#f #t #f #f #t #f #t #t #t) (#f #t #f #f #t #t #f #f #f) (#f #t #f #f #t #t #f #f #t) (#f #t #f #f #t #t #f #t #f) (#f #t #f #f #t #t #f #t #t) (#f #t #f #f #t #t #t #f #f) (#f #t #f #f #t #t #t #f #t) (#f #t #f #f #t #t #t #t #f) (#f #t #f #f #t #t #t #t #t) (#f #t #f #t #f #f #f #f #f) (#f #t #f #t #f #f #f #f #t) (#f #t #f #t #f #f #f #t #f) (#f #t #f #t #f #f #f #t #t) (#f #t #f #t #f #f #t #f #f) (#f #t #f #t #f #f #t #f #t) (#f #t #f #t #f #f #t #t #f) (#f #t #f #t #f #f #t #t #t) (#f #t #f #t #f #t #f #f #f) (#f #t #f #t #f #t #f #f #t) (#f #t #f #t #f #t #f #t #f) (#f #t #f #t #f #t #f #t #t) (#f #t #f #t #f #t #t #f #f) (#f #t #f #t #f #t #t #f #t) (#f #t #f #t #f #t #t #t #f) (#f #t #f #t #f #t #t #t #t) (#f #t #f #t #t #f #f #f #f) (#f #t #f #t #t #f #f #f #t) (#f #t #f #t #t #f #f #t #f) (#f #t #f #t #t #f #f #t #t) (#f #t #f #t #t #f #t #f #f) (#f #t #f #t #t #f #t #f #t) (#f #t #f #t #t #f #t #t #f) (#f #t #f #t #t #f #t #t #t) (#f #t #f #t #t #t #f #f #f) (#f #t #f #t #t #t #f #f #t) (#f #t #f #t #t #t #f #t #f) (#f #t #f #t #t #t #f #t #t) (#f #t #f #t #t #t #t #f #f) (#f #t #f #t #t #t #t #f #t) (#f #t #f #t #t #t #t #t #f) (#f #t #f #t #t #t #t #t #t) (#f #t #t #f #f #f #f #f #f) (#f #t #t #f #f #f #f #f #t) (#f #t #t #f #f #f #f #t #f) (#f #t #t #f #f #f #f #t #t) (#f #t #t #f #f #f #t #f #f) (#f #t #t #f #f #f #t #f #t) (#f #t #t #f #f #f #t #t #f) (#f #t #t #f #f #f #t #t #t) (#f #t #t #f #f #t #f #f #f) (#f #t #t #f #f #t #f #f #t) (#f #t #t #f #f #t #f #t #f) (#f #t #t #f #f #t #f #t #t) (#f #t #t #f #f #t #t #f #f) (#f #t #t #f #f #t #t #f #t) (#f #t #t #f #f #t #t #t #f) (#f #t #t #f #f #t #t #t #t) (#f #t #t #f #t #f #f #f #f) (#f #t #t #f #t #f #f #f #t) (#f #t #t #f #t #f #f #t #f) (#f #t #t #f #t #f #f #t #t) (#f #t #t #f #t #f #t #f #f) (#f #t #t #f #t #f #t #f #t) (#f #t #t #f #t #f #t #t #f) (#f #t #t #f #t #f #t #t #t) (#f #t #t #f #t #t #f #f #f) (#f #t #t #f #t #t #f #f #t) (#f #t #t #f #t #t #f #t #f) (#f #t #t #f #t #t #f #t #t) (#f #t #t #f #t #t #t #f #f) (#f #t #t #f #t #t #t #f #t) (#f #t #t #f #t #t #t #t #f) (#f #t #t #f #t #t #t #t #t) (#f #t #t #t #f #f #f #f #f) (#f #t #t #t #f #f #f #f #t) (#f #t #t #t #f #f #f #t #f) (#f #t #t #t #f #f #f #t #t) (#f #t #t #t #f #f #t #f #f) (#f #t #t #t #f #f #t #f #t) (#f #t #t #t #f #f #t #t #f) (#f #t #t #t #f #f #t #t #t) (#f #t #t #t #f #t #f #f #f) (#f #t #t #t #f #t #f #f #t) (#f #t #t #t #f #t #f #t #f) (#f #t #t #t #f #t #f #t #t) (#f #t #t #t #f #t #t #f #f) (#f #t #t #t #f #t #t #f #t) (#f #t #t #t #f #t #t #t #f) (#f #t #t #t #f #t #t #t #t) (#f #t #t #t #t #f #f #f #f) (#f #t #t #t #t #f #f #f #t) (#f #t #t #t #t #f #f #t #f) (#f #t #t #t #t #f #f #t #t) (#f #t #t #t #t #f #t #f #f) (#f #t #t #t #t #f #t #f #t) (#f #t #t #t #t #f #t #t #f) (#f #t #t #t #t #f #t #t #t) (#f #t #t #t #t #t #f #f #f) (#f #t #t #t #t #t #f #f #t) (#f #t #t #t #t #t #f #t #f) (#f #t #t #t #t #t #f #t #t) (#f #t #t #t #t #t #t #f #f) (#f #t #t #t #t #t #t #f #t) (#f #t #t #t #t #t #t #t #f) (#f #t #t #t #t #t #t #t #t) (#t #f #f #f #f #f #f #f #f) (#t #f #f #f #f #f #f #f #t) (#t #f #f #f #f #f #f #t #f) (#t #f #f #f #f #f #f #t #t) (#t #f #f #f #f #f #t #f #f) (#t #f #f #f #f #f #t #f #t) (#t #f #f #f #f #f #t #t #f) (#t #f #f #f #f #f #t #t #t) (#t #f #f #f #f #t #f #f #f) (#t #f #f #f #f #t #f #f #t) (#t #f #f #f #f #t #f #t #f) (#t #f #f #f #f #t #f #t #t) (#t #f #f #f #f #t #t #f #f) (#t #f #f #f #f #t #t #f #t) (#t #f #f #f #f #t #t #t #f) (#t #f #f #f #f #t #t #t #t) (#t #f #f #f #t #f #f #f #f) (#t #f #f #f #t #f #f #f #t) (#t #f #f #f #t #f #f #t #f) (#t #f #f #f #t #f #f #t #t) (#t #f #f #f #t #f #t #f #f) (#t #f #f #f #t #f #t #f #t) (#t #f #f #f #t #f #t #t #f) (#t #f #f #f #t #f #t #t #t) (#t #f #f #f #t #t #f #f #f) (#t #f #f #f #t #t #f #f #t) (#t #f #f #f #t #t #f #t #f) (#t #f #f #f #t #t #f #t #t) (#t #f #f #f #t #t #t #f #f) (#t #f #f #f #t #t #t #f #t) (#t #f #f #f #t #t #t #t #f) (#t #f #f #f #t #t #t #t #t) (#t #f #f #t #f #f #f #f #f) (#t #f #f #t #f #f #f #f #t) (#t #f #f #t #f #f #f #t #f) (#t #f #f #t #f #f #f #t #t) (#t #f #f #t #f #f #t #f #f) (#t #f #f #t #f #f #t #f #t) (#t #f #f #t #f #f #t #t #f) (#t #f #f #t #f #f #t #t #t) (#t #f #f #t #f #t #f #f #f) (#t #f #f #t #f #t #f #f #t) (#t #f #f #t #f #t #f #t #f) (#t #f #f #t #f #t #f #t #t) (#t #f #f #t #f #t #t #f #f) (#t #f #f #t #f #t #t #f #t) (#t #f #f #t #f #t #t #t #f) (#t #f #f #t #f #t #t #t #t) (#t #f #f #t #t #f #f #f #f) (#t #f #f #t #t #f #f #f #t) (#t #f #f #t #t #f #f #t #f) (#t #f #f #t #t #f #f #t #t) (#t #f #f #t #t #f #t #f #f) (#t #f #f #t #t #f #t #f #t) (#t #f #f #t #t #f #t #t #f) (#t #f #f #t #t #f #t #t #t) (#t #f #f #t #t #t #f #f #f) (#t #f #f #t #t #t #f #f #t) (#t #f #f #t #t #t #f #t #f) (#t #f #f #t #t #t #f #t #t) (#t #f #f #t #t #t #t #f #f) (#t #f #f #t #t #t #t #f #t) (#t #f #f #t #t #t #t #t #f) (#t #f #f #t #t #t #t #t #t) (#t #f #t #f #f #f #f #f #f) (#t #f #t #f #f #f #f #f #t) (#t #f #t #f #f #f #f #t #f) (#t #f #t #f #f #f #f #t #t) (#t #f #t #f #f #f #t #f #f) (#t #f #t #f #f #f #t #f #t) (#t #f #t #f #f #f #t #t #f) (#t #f #t #f #f #f #t #t #t) (#t #f #t #f #f #t #f #f #f) (#t #f #t #f #f #t #f #f #t) (#t #f #t #f #f #t #f #t #f) (#t #f #t #f #f #t #f #t #t) (#t #f #t #f #f #t #t #f #f) (#t #f #t #f #f #t #t #f #t) (#t #f #t #f #f #t #t #t #f) (#t #f #t #f #f #t #t #t #t) (#t #f #t #f #t #f #f #f #f) (#t #f #t #f #t #f #f #f #t) (#t #f #t #f #t #f #f #t #f) (#t #f #t #f #t #f #f #t #t) (#t #f #t #f #t #f #t #f #f) (#t #f #t #f #t #f #t #f #t) (#t #f #t #f #t #f #t #t #f) (#t #f #t #f #t #f #t #t #t) (#t #f #t #f #t #t #f #f #f) (#t #f #t #f #t #t #f #f #t) (#t #f #t #f #t #t #f #t #f) (#t #f #t #f #t #t #f #t #t) (#t #f #t #f #t #t #t #f #f) (#t #f #t #f #t #t #t #f #t) (#t #f #t #f #t #t #t #t #f) (#t #f #t #f #t #t #t #t #t) (#t #f #t #t #f #f #f #f #f) (#t #f #t #t #f #f #f #f #t) (#t #f #t #t #f #f #f #t #f) (#t #f #t #t #f #f #f #t #t) (#t #f #t #t #f #f #t #f #f) (#t #f #t #t #f #f #t #f #t) (#t #f #t #t #f #f #t #t #f) (#t #f #t #t #f #f #t #t #t) (#t #f #t #t #f #t #f #f #f) (#t #f #t #t #f #t #f #f #t) (#t #f #t #t #f #t #f #t #f) (#t #f #t #t #f #t #f #t #t) (#t #f #t #t #f #t #t #f #f) (#t #f #t #t #f #t #t #f #t) (#t #f #t #t #f #t #t #t #f) (#t #f #t #t #f #t #t #t #t) (#t #f #t #t #t #f #f #f #f) (#t #f #t #t #t #f #f #f #t) (#t #f #t #t #t #f #f #t #f) (#t #f #t #t #t #f #f #t #t) (#t #f #t #t #t #f #t #f #f) (#t #f #t #t #t #f #t #f #t) (#t #f #t #t #t #f #t #t #f) (#t #f #t #t #t #f #t #t #t) (#t #f #t #t #t #t #f #f #f) (#t #f #t #t #t #t #f #f #t) (#t #f #t #t #t #t #f #t #f) (#t #f #t #t #t #t #f #t #t) (#t #f #t #t #t #t #t #f #f) (#t #f #t #t #t #t #t #f #t) (#t #f #t #t #t #t #t #t #f) (#t #f #t #t #t #t #t #t #t) (#t #t #f #f #f #f #f #f #f) (#t #t #f #f #f #f #f #f #t) (#t #t #f #f #f #f #f #t #f) (#t #t #f #f #f #f #f #t #t) (#t #t #f #f #f #f #t #f #f) (#t #t #f #f #f #f #t #f #t) (#t #t #f #f #f #f #t #t #f) (#t #t #f #f #f #f #t #t #t) (#t #t #f #f #f #t #f #f #f) (#t #t #f #f #f #t #f #f #t) (#t #t #f #f #f #t #f #t #f) (#t #t #f #f #f #t #f #t #t) (#t #t #f #f #f #t #t #f #f) (#t #t #f #f #f #t #t #f #t) (#t #t #f #f #f #t #t #t #f) (#t #t #f #f #f #t #t #t #t) (#t #t #f #f #t #f #f #f #f) (#t #t #f #f #t #f #f #f #t) (#t #t #f #f #t #f #f #t #f) (#t #t #f #f #t #f #f #t #t) (#t #t #f #f #t #f #t #f #f) (#t #t #f #f #t #f #t #f #t) (#t #t #f #f #t #f #t #t #f) (#t #t #f #f #t #f #t #t #t) (#t #t #f #f #t #t #f #f #f) (#t #t #f #f #t #t #f #f #t) (#t #t #f #f #t #t #f #t #f) (#t #t #f #f #t #t #f #t #t) (#t #t #f #f #t #t #t #f #f) (#t #t #f #f #t #t #t #f #t) (#t #t #f #f #t #t #t #t #f) (#t #t #f #f #t #t #t #t #t) (#t #t #f #t #f #f #f #f #f) (#t #t #f #t #f #f #f #f #t) (#t #t #f #t #f #f #f #t #f) (#t #t #f #t #f #f #f #t #t) (#t #t #f #t #f #f #t #f #f) (#t #t #f #t #f #f #t #f #t) (#t #t #f #t #f #f #t #t #f) (#t #t #f #t #f #f #t #t #t) (#t #t #f #t #f #t #f #f #f) (#t #t #f #t #f #t #f #f #t) (#t #t #f #t #f #t #f #t #f) (#t #t #f #t #f #t #f #t #t) (#t #t #f #t #f #t #t #f #f) (#t #t #f #t #f #t #t #f #t) (#t #t #f #t #f #t #t #t #f) (#t #t #f #t #f #t #t #t #t) (#t #t #f #t #t #f #f #f #f) (#t #t #f #t #t #f #f #f #t) (#t #t #f #t #t #f #f #t #f) (#t #t #f #t #t #f #f #t #t) (#t #t #f #t #t #f #t #f #f) (#t #t #f #t #t #f #t #f #t) (#t #t #f #t #t #f #t #t #f) (#t #t #f #t #t #f #t #t #t) (#t #t #f #t #t #t #f #f #f) (#t #t #f #t #t #t #f #f #t) (#t #t #f #t #t #t #f #t #f) (#t #t #f #t #t #t #f #t #t) (#t #t #f #t #t #t #t #f #f) (#t #t #f #t #t #t #t #f #t) (#t #t #f #t #t #t #t #t #f) (#t #t #f #t #t #t #t #t #t) (#t #t #t #f #f #f #f #f #f) (#t #t #t #f #f #f #f #f #t) (#t #t #t #f #f #f #f #t #f) (#t #t #t #f #f #f #f #t #t) (#t #t #t #f #f #f #t #f #f) (#t #t #t #f #f #f #t #f #t) (#t #t #t #f #f #f #t #t #f) (#t #t #t #f #f #f #t #t #t) (#t #t #t #f #f #t #f #f #f) (#t #t #t #f #f #t #f #f #t) (#t #t #t #f #f #t #f #t #f) (#t #t #t #f #f #t #f #t #t) (#t #t #t #f #f #t #t #f #f) (#t #t #t #f #f #t #t #f #t) (#t #t #t #f #f #t #t #t #f) (#t #t #t #f #f #t #t #t #t) (#t #t #t #f #t #f #f #f #f) (#t #t #t #f #t #f #f #f #t) (#t #t #t #f #t #f #f #t #f) (#t #t #t #f #t #f #f #t #t) (#t #t #t #f #t #f #t #f #f) (#t #t #t #f #t #f #t #f #t) (#t #t #t #f #t #f #t #t #f) (#t #t #t #f #t #f #t #t #t) (#t #t #t #f #t #t #f #f #f) (#t #t #t #f #t #t #f #f #t) (#t #t #t #f #t #t #f #t #f) (#t #t #t #f #t #t #f #t #t) (#t #t #t #f #t #t #t #f #f) (#t #t #t #f #t #t #t #f #t) (#t #t #t #f #t #t #t #t #f) (#t #t #t #f #t #t #t #t #t) (#t #t #t #t #f #f #f #f #f) (#t #t #t #t #f #f #f #f #t) (#t #t #t #t #f #f #f #t #f) (#t #t #t #t #f #f #f #t #t) (#t #t #t #t #f #f #t #f #f) (#t #t #t #t #f #f #t #f #t) (#t #t #t #t #f #f #t #t #f) (#t #t #t #t #f #f #t #t #t) (#t #t #t #t #f #t #f #f #f) (#t #t #t #t #f #t #f #f #t) (#t #t #t #t #f #t #f #t #f) (#t #t #t #t #f #t #f #t #t) (#t #t #t #t #f #t #t #f #f) (#t #t #t #t #f #t #t #f #t) (#t #t #t #t #f #t #t #t #f) (#t #t #t #t #f #t #t #t #t) (#t #t #t #t #t #f #f #f #f) (#t #t #t #t #t #f #f #f #t) (#t #t #t #t #t #f #f #t #f) (#t #t #t #t #t #f #f #t #t) (#t #t #t #t #t #f #t #f #f) (#t #t #t #t #t #f #t #f #t) (#t #t #t #t #t #f #t #t #f) (#t #t #t #t #t #f #t #t #t) (#t #t #t #t #t #t #f #f #f) (#t #t #t #t #t #t #f #f #t) (#t #t #t #t #t #t #f #t #f) (#t #t #t #t #t #t #f #t #t) (#t #t #t #t #t #t #t #f #f) (#t #t #t #t #t #t #t #f #t) (#t #t #t #t #t #t #t #t #f) (#t #t #t #t #t #t #t #t #t))
		(if (< (list-length var_list) 11) ; checks for 10 arguments and outputs that this program is limited to 9 variable input
		"This Number of Entries Not Supported"
	)))))))))))) ; function end