run: problem1.py problem2.py problem3.py view
	#chmod u+x problem1.py 
		python problem1.py
	#chmod u+x problem2.py
		python problem2.py
	#chmod u+x problem3.py
		python problem3.py
	#chmod u+x view
		./view

clean :
		- \rm $(outFile) *~ > /dev/null 2>&1

