run: byHand viewHand byGen viewGen clean
	#chmod u+x byHand 
		python byHand < byHandTest 
	#chmod u+x viewHand
		./viewHand
	#chmod u+x byGen
	  python byGen < byGenTest 
	#chmod u+x viewGen
	  ./viewHand
	#chmod u+x clean
		./clean

clean :
	- \rm $(outFile) *~ > /dev/null 2>&1


