run: prob1.py timefunction.py view
	#chmod u+x prob1.py 
		python prob1.py
	#chmod u+x timefunction.py
		python timefunction.py
	#chmod u+x view
		./view

clean :
		- \rm $(outFile) *~ > /dev/null 2>&1

