run: graph.py sim.py clean
	#chmod u+x graph.py 
		python graph.py sample1.input
	#chmod u+x sim.py
		python sim.py sample1.input
	#chmod u+x view
		./clean

clean :
	- \rm $(outFile) *~ > /dev/null 2>&1


